export const TIMERS = [
  {
    id: 'amrap',
    name: 'AMRAP',
    full: 'Un maximum de tours dans le temps donné',
    tag: 'ENDURANCE',
    color: '#FF5454',
    bgColors: ['#FF5454', '#B81818', '#4A0606'],
    textMode: 'light',
    defaultStats: { duration: 20 },
    phases: ['ÉCHAUFFEMENT', 'AMRAP', "RÉCUP'"],
  },
  {
    id: 'basic',
    name: 'BASIC',
    full: 'Alterne travail et pause librement',
    tag: 'STANDARD',
    color: '#9A9A9A',
    bgColors: ['#3A3A3A', '#1A1A1A', '#050505'],
    textMode: 'light',
    defaultStats: { work: 60, rest: 30, rounds: 3 },
    phases: ['TRAVAIL', 'PAUSE'],
  },
  {
    id: 'emom',
    name: 'EMOM',
    full: 'Un effort à chaque début de minute',
    tag: 'RYTHME',
    color: '#1FC777',
    bgColors: ['#1FC777', '#047442', '#022A18'],
    textMode: 'light',
    defaultStats: { interval: 60, rounds: 10 },
    phases: ['T1', 'T2', 'T3', '...'],
  },
  {
    id: 'tabata',
    name: 'TABATA',
    full: '20s travail / 10s repos',
    tag: 'HIIT',
    color: '#FFC933',
    bgColors: ['#FFC933', '#E08500', '#5C2E00'],
    textMode: 'dark',
    defaultStats: { work: 20, rest: 10, rounds: 8 },
    phases: ['T', 'R', 'T', 'R'],
  },
  {
    id: 'mix',
    name: 'MIX',
    full: 'Enchaînement personnalisé de plusieurs timers',
    tag: 'COMBINÉ',
    color: '#9575FF',
    bgColors: ['#9575FF', '#4B2FC9', '#1A0D52'],
    textMode: 'light',
    defaultStats: {},
    phases: ['AMRAP', 'EMOM', 'TABATA', '...'],
  },
];
